version: '3'

services:
  web:
    image: recruit_challenge:rc2
    build: .
    
    command: >
      sh -c "python manage.py migrate &&
             python manage.py test &&   
             python manage.py import_customers &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      
      
    volumes:
      - data:/code
      

volumes:
  data: